const VERSION = '0.1.0';
const WORKER = 'afo-github-actions-investigator-mcp';
const GH = 'https://api.github.com';
const MODEL = '@cf/meta/llama-3.3-70b-instruct-fp8-fast';
const CORS = {'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization, Mcp-Session-Id'};
function j(x,s=200){return new Response(JSON.stringify(x,null,2),{status:s,headers:{...CORS,'content-type':'application/json;charset=utf-8','cache-control':'no-store'}})}
async function body(r){try{return await r.json()}catch{return {}}}
const c=v=>String(v||'').trim();
const a=v=>Array.isArray(v)?v:[];
function n(v,d,min,max){v=Number(v);return Number.isFinite(v)?Math.max(min,Math.min(max,v)):d}
function owner(env,args){return c(args.owner||env.DEFAULT_OWNER||'nothinginfinity')}
function repo(args){return c(args.repo)||'afo-visual-browser-subagent-mcp'}
function token(env){return c(env.GITHUB_TOKEN||env.GH_TOKEN)}
function hdr(env,accept='application/vnd.github+json'){const h={accept,'user-agent':`${WORKER}/${VERSION}`,'x-github-api-version':'2022-11-28'};const t=token(env);if(t)h.authorization=`Bearer ${t}`;return h}
function q(o){const u=new URLSearchParams();for(const[k,v]of Object.entries(o||{}))if(v!==undefined&&v!==null&&v!=='')u.set(k,String(v));const s=u.toString();return s?`?${s}`:''}
async function gh(env,path,query){const r=await fetch(GH+path+q(query),{headers:hdr(env)});const txt=await r.text();let x;try{x=JSON.parse(txt)}catch{x={raw:txt}}if(!r.ok)throw new Error(`GitHub GET ${path} -> ${r.status}: ${x.message||txt.slice(0,220)}`);return x}
async function ght(env,path,query){const r=await fetch(GH+path+q(query),{headers:hdr(env)});const txt=await r.text();if(!r.ok){let m=txt.slice(0,220);try{m=JSON.parse(txt).message||m}catch{}throw new Error(`GitHub GET ${path} -> ${r.status}: ${m}`)}return {content_type:r.headers.get('content-type')||'',text:txt}}
function dec(s){const raw=atob(String(s||'').replace(/\n/g,''));const b=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)b[i]=raw.charCodeAt(i);return new TextDecoder().decode(b)}
function ep(p){return c(p).split('/').map(encodeURIComponent).join('/')}
function wb(v){const p=c(v).split('/').filter(Boolean);return p[p.length-1]||c(v)}
function cw(w){return {id:w.id,name:w.name,path:w.path,state:w.state,created_at:w.created_at,updated_at:w.updated_at,html_url:w.html_url}}
function cr(r){return {id:r.id,name:r.name,workflow_id:r.workflow_id,event:r.event,status:r.status,conclusion:r.conclusion,head_branch:r.head_branch,head_sha:r.head_sha,display_title:r.display_title,run_number:r.run_number,run_attempt:r.run_attempt,actor:r.actor&&r.actor.login,triggering_actor:r.triggering_actor&&r.triggering_actor.login,created_at:r.created_at,updated_at:r.updated_at,run_started_at:r.run_started_at,html_url:r.html_url}}
function cj(j){return {id:j.id,run_id:j.run_id,name:j.name,status:j.status,conclusion:j.conclusion,started_at:j.started_at,completed_at:j.completed_at,html_url:j.html_url,runner_name:j.runner_name||null,labels:j.labels||[],steps:a(j.steps).map(s=>({name:s.name,status:s.status,conclusion:s.conclusion,number:s.number,started_at:s.started_at,completed_at:s.completed_at}))}}
function badSteps(job){return a(job.steps).filter(s=>s.conclusion&&s.conclusion!=='success'&&s.conclusion!=='skipped')}
function badJobs(jobs){return a(jobs).filter(j=>j.conclusion&&j.conclusion!=='success'&&j.conclusion!=='skipped')}
function summary(run,jobs){const bj=badJobs(jobs);return {run:run&&{id:run.id,name:run.name,event:run.event,status:run.status,conclusion:run.conclusion,head_branch:run.head_branch,head_sha:run.head_sha,run_attempt:run.run_attempt,html_url:run.html_url},failed_job_count:bj.length,failed_jobs:bj.map(j=>({id:j.id,name:j.name,conclusion:j.conclusion,failed_steps:badSteps(j).map(s=>({name:s.name,conclusion:s.conclusion,number:s.number}))}))}}
function trim(txt,max,tail=true){txt=String(txt||'');if(txt.length<=max)return {text:txt,truncated:false,total_chars:txt.length,slice:'full'};if(tail)return {text:txt.slice(-max),truncated:true,total_chars:txt.length,slice:'tail'};const h=Math.floor(max/2);return {text:txt.slice(0,h)+'\n\n--- LOG MIDDLE TRUNCATED ---\n\n'+txt.slice(-h),truncated:true,total_chars:txt.length,slice:'head_tail'}}
function time(){const t0=Date.now(),s={};let k,st;return {go(x){if(k)s[k]=(s[k]||0)+Date.now()-st;k=x;st=Date.now()},done(){if(k)s[k]=(s[k]||0)+Date.now()-st;return {stages_ms:s,total_ms:Date.now()-t0}}}}
async function listWorkflows(env,args={}){const o=owner(env,args),r=repo(args),limit=n(args.limit,50,1,100);const x=await gh(env,`/repos/${encodeURIComponent(o)}/${encodeURIComponent(r)}/actions/workflows`,{per_page:limit});let ws=a(x.workflows).map(cw);const qq=c(args.query).toLowerCase();if(qq)ws=ws.filter(w=>`${w.id} ${w.name} ${w.path}`.toLowerCase().includes(qq));return {ok:true,owner:o,repo:r,total_count:x.total_count,count:ws.length,workflows:ws}}
async function resolveWorkflow(env,o,r,args={}){const raw=c(args.workflow_id||args.workflow||args.workflow_name||args.workflow_path);if(!raw)return null;const ws=(await listWorkflows(env,{owner:o,repo:r,limit:100})).workflows;const want=raw.toLowerCase(),base=wb(raw).toLowerCase();return ws.find(w=>String(w.id)===raw||c(w.name).toLowerCase()===want||c(w.path).toLowerCase()===want||wb(w.path).toLowerCase()===base||c(w.name).toLowerCase().includes(want))||{id:wb(raw),name:raw,path:raw,unresolved:true}}
async function listRuns(env,args={}){const o=owner(env,args),r=repo(args),limit=n(args.limit,10,1,100),query={per_page:limit};for(const [k,v] of Object.entries({branch:args.branch||args.ref,status:args.status,event:args.event,actor:args.actor,created:args.created,head_sha:args.head_sha||args.sha||args.commit_sha}))if(c(v))query[k]=c(v);const wf=await resolveWorkflow(env,o,r,args);const path=wf?`/repos/${encodeURIComponent(o)}/${encodeURIComponent(r)}/actions/workflows/${encodeURIComponent(String(wf.id))}/runs`:`/repos/${encodeURIComponent(o)}/${encodeURIComponent(r)}/actions/runs`;const x=await gh(env,path,query);let runs=a(x.workflow_runs).map(cr);if(wf&&wf.unresolved){const z=c(args.workflow||args.workflow_name||args.workflow_path).toLowerCase();runs=runs.filter(run=>c(run.name).toLowerCase().includes(z))}return {ok:true,owner:o,repo:r,workflow:wf,query,total_count:x.total_count,count:runs.length,runs}}
async function inspectRun(env,args={}){const o=owner(env,args),r=repo(args),id=c(args.run_id||args.id);if(!id)return {ok:false,error:'run_id is required'};const tr=time();tr.go('run');const run=cr(await gh(env,`/repos/${encodeURIComponent(o)}/${encodeURIComponent(r)}/actions/runs/${encodeURIComponent(id)}`));tr.go('jobs');const jobs=a((await gh(env,`/repos/${encodeURIComponent(o)}/${encodeURIComponent(r)}/actions/runs/${encodeURIComponent(id)}/jobs`,{per_page:100})).jobs).map(cj);let logs=[];if(args.include_logs){tr.go('job_logs');logs=await Promise.all(badJobs(jobs).slice(0,n(args.log_job_limit,3,1,10)).map(async job=>{try{const x=await ght(env,`/repos/${encodeURIComponent(o)}/${encodeURIComponent(r)}/actions/jobs/${encodeURIComponent(job.id)}/logs`);return {ok:true,job_id:job.id,job_name:job.name,...trim(x.text,n(args.max_log_chars,12000,1000,60000),true)}}catch(e){return {ok:false,job_id:job.id,job_name:job.name,error:String(e.message||e)}}}))}return {ok:true,owner:o,repo:r,run,jobs,failure_summary:summary(run,jobs),logs,timings:tr.done()}}
async function readJobLog(env,args={}){const o=owner(env,args),r=repo(args),id=c(args.job_id||args.id);if(!id)return {ok:false,error:'job_id is required'};const x=await ght(env,`/repos/${encodeURIComponent(o)}/${encodeURIComponent(r)}/actions/jobs/${encodeURIComponent(id)}/logs`);return {ok:true,owner:o,repo:r,job_id:id,content_type:x.content_type,...trim(x.text,n(args.max_chars,30000,1000,120000),args.tail_only!==false)}}
async function readWorkflowFile(env,args={}){const o=owner(env,args),r=repo(args),ref=c(args.ref||args.branch||'main');let path=c(args.path||args.workflow_path),wf=null;if(!path){wf=await resolveWorkflow(env,o,r,args);path=wf&&!wf.unresolved?wf.path:c(args.workflow||args.workflow_name||args.workflow_id)}if(!path)return {ok:false,error:'workflow path or identifier is required'};const x=await gh(env,`/repos/${encodeURIComponent(o)}/${encodeURIComponent(r)}/contents/${ep(path)}`,{ref});const text=dec(x.content||''),max=n(args.max_chars,40000,1000,120000);return {ok:true,owner:o,repo:r,ref,path,workflow:wf,sha:x.sha,size:x.size,truncated:text.length>max,text:text.slice(0,max),total_chars:text.length}}
async function findRunsForSha(env,args={}){const sha=c(args.sha||args.head_sha||args.commit_sha);if(!sha)return {ok:false,error:'sha is required'};return {...await listRuns(env,{...args,head_sha:sha,limit:n(args.limit,20,1,100)}),sha}}
async function ai(env,evidence,question){if(!env.AI)return null;const prompt='Use only this JSON evidence. Explain whether the GitHub Actions workflow ran, where it failed, failed job/step, branch, event, commit SHA, likely cause, and uncertainty. Recommend read-only next checks only.\n\nQuestion: '+question+'\n\nEvidence:\n'+JSON.stringify(evidence,null,2).slice(0,42000);const out=await env.AI.run(MODEL,{messages:[{role:'user',content:prompt}],max_tokens:1800});return c(out.response||out.result||out.output_text)}
function fallback(e){const s=e.failure_summary||{},run=s.run||{};if(!run.id)return 'No workflow run was selected or found.';let out=`Workflow run ${run.id} (${run.name||'unnamed'}) is ${run.status||'unknown'} with conclusion ${run.conclusion||'none'}.\nTrigger context: event=${run.event||'unknown'}, branch=${run.head_branch||'unknown'}, sha=${run.head_sha||'unknown'}.`;if(s.failed_job_count){for(const j of s.failed_jobs)out+=`\nFailed job: ${j.name} [${j.conclusion}]. Failed steps: ${(j.failed_steps||[]).map(st=>st.name+' ['+st.conclusion+']').join(', ')||'not reported'}.`}else out+='\nNo failed job was reported in the job list.';if(e.workflow_file&&e.workflow_file.path)out+=`\nWorkflow file inspected: ${e.workflow_file.path}.`;return out}
async function investigate(env,args={}){const tr=time();let id=c(args.run_id||args.id),runs=null;tr.go('select_run');if(!id){runs=await listRuns(env,{...args,status:c(args.status||'completed'),limit:n(args.run_limit,20,1,100)});const sel=a(runs.runs).find(r=>r.conclusion&&r.conclusion!=='success')||a(runs.runs)[0];id=sel?String(sel.id):''}if(!id)return {ok:false,error:'No workflow run found to inspect',runs};tr.go('inspect_run');const inspected=await inspectRun(env,{...args,run_id:id,include_logs:args.include_logs!==false,max_log_chars:n(args.max_log_chars,12000,1000,60000),log_job_limit:n(args.log_job_limit,3,1,10)});tr.go('workflow_file');let wf;try{wf=await readWorkflowFile(env,{owner:inspected.owner,repo:inspected.repo,workflow_id:inspected.run.workflow_id,ref:c(args.workflow_ref||inspected.run.head_branch||args.branch||'main'),max_chars:n(args.workflow_max_chars,30000,1000,80000)})}catch(e){wf={ok:false,error:String(e.message||e)}}const evidence={selected_from_runs:runs&&{count:runs.count,total_count:runs.total_count,query:runs.query,first_runs:a(runs.runs).slice(0,10)},run:inspected.run,jobs:inspected.jobs,failure_summary:inspected.failure_summary,logs:inspected.logs,workflow_file:wf&&wf.ok?{path:wf.path,sha:wf.sha,text:wf.text,truncated:wf.truncated}:wf};tr.go('synthesis');const answer=await ai(env,evidence,c(args.question||'Explain the latest non-success GitHub Actions run and identify the failed job or step.')).catch(()=>null)||fallback(evidence);return {ok:true,answer,flow:'github_actions_failure_investigation',evidence:args.include_raw?evidence:{run:evidence.run,failure_summary:evidence.failure_summary,logs:a(evidence.logs).map(l=>({ok:l.ok,job_id:l.job_id,job_name:l.job_name,truncated:l.truncated,total_chars:l.total_chars,error:l.error||null})),workflow_file:evidence.workflow_file&&evidence.workflow_file.ok===false?evidence.workflow_file:evidence.workflow_file?{path:evidence.workflow_file.path,sha:evidence.workflow_file.sha,truncated:evidence.workflow_file.truncated}:null,selected_from_runs:evidence.selected_from_runs},timings:tr.done()}}
function status(env){return {ok:true,worker:WORKER,deployed_as:env.WORKER_NAME||null,version:VERSION,mode:'read_only_github_actions_investigator',model_default:MODEL,bindings:{AI:!!env.AI,WORKER_NAME:!!env.WORKER_NAME,GITHUB_TOKEN:!!token(env),DEFAULT_OWNER:!!env.DEFAULT_OWNER},tools:['subagent_status','list_workflows','list_workflow_runs','inspect_workflow_run','read_job_log','read_workflow_file','find_runs_for_sha','investigate_actions_failure']}}
const schema=[
{name:'subagent_status',description:'Health check: GitHub Actions investigator bindings, read-only mode, model, and tool list.',inputSchema:{type:'object',properties:{},required:[]}},
{name:'list_workflows',description:'List GitHub Actions workflow files for a repo. Read-only CI inventory.',inputSchema:{type:'object',properties:{owner:{type:'string'},repo:{type:'string'},query:{type:'string'},limit:{type:'number'}},required:[]}},
{name:'list_workflow_runs',description:'List recent GitHub Actions runs by repo, workflow, branch, event, status, actor, date window, or commit SHA. Read-only CI evidence.',inputSchema:{type:'object',properties:{owner:{type:'string'},repo:{type:'string'},workflow:{type:'string'},workflow_id:{type:'string'},workflow_name:{type:'string'},workflow_path:{type:'string'},branch:{type:'string'},ref:{type:'string'},status:{type:'string'},event:{type:'string'},actor:{type:'string'},created:{type:'string'},sha:{type:'string'},head_sha:{type:'string'},commit_sha:{type:'string'},limit:{type:'number'}},required:[]}},
{name:'inspect_workflow_run',description:'Inspect one GitHub Actions run by run_id, including jobs, step conclusions, failed steps, branch, event, and commit SHA. Optional read-only job log excerpts.',inputSchema:{type:'object',properties:{owner:{type:'string'},repo:{type:'string'},run_id:{type:'string'},id:{type:'string'},include_logs:{type:'boolean'},max_log_chars:{type:'number'},log_job_limit:{type:'number'}},required:[]}},
{name:'read_job_log',description:'Read one GitHub Actions job log by job_id. Read-only log excerpt for diagnosis.',inputSchema:{type:'object',properties:{owner:{type:'string'},repo:{type:'string'},job_id:{type:'string'},id:{type:'string'},max_chars:{type:'number'},tail_only:{type:'boolean'}},required:[]}},
{name:'read_workflow_file',description:'Read the workflow YAML for trigger and job context by path, workflow id, workflow name, or workflow filename. Read-only.',inputSchema:{type:'object',properties:{owner:{type:'string'},repo:{type:'string'},ref:{type:'string'},branch:{type:'string'},path:{type:'string'},workflow_path:{type:'string'},workflow:{type:'string'},workflow_id:{type:'string'},workflow_name:{type:'string'},max_chars:{type:'number'}},required:[]}},
{name:'find_runs_for_sha',description:'Find GitHub Actions runs associated with a commit SHA. Read-only CI evidence lookup.',inputSchema:{type:'object',properties:{owner:{type:'string'},repo:{type:'string'},sha:{type:'string'},head_sha:{type:'string'},commit_sha:{type:'string'},workflow:{type:'string'},branch:{type:'string'},status:{type:'string'},limit:{type:'number'}},required:[]}},
{name:'investigate_actions_failure',description:'ONE-CALL GitHub Actions investigation: select a run, inspect jobs and failed steps, read workflow YAML, optionally read failed job logs, then return an evidence-grounded failure explanation. Read-only.',inputSchema:{type:'object',properties:{owner:{type:'string'},repo:{type:'string'},run_id:{type:'string'},id:{type:'string'},workflow:{type:'string'},workflow_id:{type:'string'},workflow_name:{type:'string'},workflow_path:{type:'string'},branch:{type:'string'},ref:{type:'string'},status:{type:'string'},event:{type:'string'},question:{type:'string'},include_logs:{type:'boolean'},include_raw:{type:'boolean'},max_log_chars:{type:'number'},log_job_limit:{type:'number'},run_limit:{type:'number'},workflow_ref:{type:'string'},workflow_max_chars:{type:'number'}},required:[]}}
];
async function call(env,name,args){if(name==='subagent_status')return status(env);if(name==='list_workflows')return listWorkflows(env,args||{});if(name==='list_workflow_runs')return listRuns(env,args||{});if(name==='inspect_workflow_run')return inspectRun(env,args||{});if(name==='read_job_log')return readJobLog(env,args||{});if(name==='read_workflow_file')return readWorkflowFile(env,args||{});if(name==='find_runs_for_sha')return findRunsForSha(env,args||{});if(name==='investigate_actions_failure')return investigate(env,args||{});throw new Error('Unknown tool: '+name)}
async function mcp(req,env){const rpc=await body(req),id=rpc.id==null?null:rpc.id;try{if(rpc.method==='initialize')return j({jsonrpc:'2.0',id,result:{protocolVersion:'2024-11-05',capabilities:{tools:{}},serverInfo:{name:WORKER,version:VERSION}}});if(rpc.method==='notifications/initialized')return new Response(null,{status:204,headers:CORS});if(rpc.method==='ping')return j({jsonrpc:'2.0',id,result:{}});if(rpc.method==='tools/list')return j({jsonrpc:'2.0',id,result:{tools:schema}});if(rpc.method==='tools/call'){let result;try{result=await call(env,rpc.params&&rpc.params.name,rpc.params&&rpc.params.arguments||{})}catch(e){result={ok:false,error:String(e.message||e)}}return j({jsonrpc:'2.0',id,result:{content:[{type:'text',text:JSON.stringify(result,null,2)}],isError:result&&result.ok===false}})}return j({jsonrpc:'2.0',id,error:{code:-32601,message:'Method not found'}})}catch(e){return j({jsonrpc:'2.0',id,error:{code:-32603,message:String(e.message||e)}})}}
export default {async fetch(req,env){const url=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});try{if(url.pathname==='/'||url.pathname==='/status'||url.pathname==='/health')return j(status(env));if(url.pathname==='/tools')return j({ok:true,tools:schema});if(url.pathname==='/mcp')return mcp(req,env);if(req.method==='POST'&&url.pathname==='/call'){const b=await body(req);try{return j(await call(env,b.name,b.arguments||{}))}catch(e){return j({ok:false,error:String(e.message||e)},200)}}return j({ok:false,error:'not_found',worker:WORKER},404)}catch(e){return j({ok:false,error:String(e.message||e),worker:WORKER},500)}}};