const V='0.1.0',W='afo-binding-investigator-mcp',CF='https://api.cloudflare.com/client/v4',GH='https://api.github.com';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization, Mcp-Session-Id'};
const s=x=>String(x??'').trim(), A=x=>Array.isArray(x)?x:[], O=x=>x&&typeof x==='object'&&!Array.isArray(x), csv=x=>Array.isArray(x)?x.map(s).filter(Boolean):s(x).split(',').map(s).filter(Boolean);
function J(x,n=200){return new Response(JSON.stringify(x,null,2),{status:n,headers:{...C,'content-type':'application/json;charset=utf-8','cache-control':'no-store'}})}
async function B(r){try{return await r.json()}catch{return{}}}
function acct(e,a={}){return s(a.account_id||e.CLOUDFLARE_ACCOUNT_ID||e.CF_ACCOUNT_ID||e.ACCOUNT_ID)}
function cftok(e){return s(e.CLOUDFLARE_API_TOKEN||e.CF_API_TOKEN||e.CLOUDFLARE_TOKEN)}
function ghtok(e){return s(e.GITHUB_TOKEN||e.GH_TOKEN)}
function own(e,a={}){return s(a.owner||e.DEFAULT_OWNER||'nothinginfinity')}
function repo(e,a={}){return s(a.repo||e.DEFAULT_REPO||'afo-visual-browser-subagent-mcp')}
function script(e,a={}){return s(a.script_name||a.worker||a.worker_name||e.DEFAULT_SCRIPT_NAME||'afo-cloudflare-deploy-investigator-mcp')}
function wp(e,a={}){return s(a.wrangler_path||a.path||a.config_path||e.DEFAULT_WRANGLER_PATH||'subagents/cloudflare-deploy-investigator/wrangler.jsonc')}
function q(o={}){const u=new URLSearchParams();for(const[k,v]of Object.entries(o))if(v!==undefined&&v!==null&&v!=='')u.set(k,String(v));return u.toString()?'?'+u.toString():''}
function ep(p){return s(p).split('/').map(encodeURIComponent).join('/')}
function dec(x){const r=atob(String(x||'').replace(/\n/g,'')),b=new Uint8Array(r.length);for(let i=0;i<r.length;i++)b[i]=r.charCodeAt(i);return new TextDecoder().decode(b)}
function jsonc(t){let o='',str=0,esc=0,line=0,blk=0;t=String(t||'');for(let i=0;i<t.length;i++){let c=t[i],n=t[i+1];if(line){if(c==='\n'){line=0;o+=c}continue}if(blk){if(c==='*'&&n==='/'){blk=0;i++}continue}if(str){o+=c;if(esc)esc=0;else if(c==='\\')esc=1;else if(c==='"')str=0;continue}if(c==='"'){str=1;o+=c;continue}if(c==='/'&&n==='/'){line=1;i++;continue}if(c==='/'&&n==='*'){blk=1;i++;continue}o+=c}return JSON.parse(o.replace(/,\s*([}\]])/g,'$1'))}
async function gh(e,p,qq){const h={accept:'application/vnd.github+json','user-agent':W+'/'+V,'x-github-api-version':'2022-11-28'};let t=ghtok(e);if(t)h.authorization='Bearer '+t;const r=await fetch(GH+p+q(qq),{headers:h}),txt=await r.text();let x;try{x=JSON.parse(txt)}catch{x={raw:txt}}if(!r.ok)throw Error(`GitHub GET ${p} -> ${r.status}: ${x.message||txt.slice(0,180)}`);return x}
async function cf(e,a,m,p,qq){let id=acct(e,a),t=cftok(e);if(!id)throw Error('Cloudflare account_id is required.');if(!t)throw Error('Cloudflare API token is required as Worker secret.');const r=await fetch(CF+p.replaceAll('{account_id}',encodeURIComponent(id))+q(qq),{method:m,headers:{authorization:'Bearer '+t,accept:'application/json'}}),txt=await r.text();let x;try{x=JSON.parse(txt)}catch{x={raw:txt}}if(!r.ok||x.success===false)throw Error(`Cloudflare ${m} ${p} -> ${r.status}: ${JSON.stringify(x.errors||x).slice(0,260)}`);return x.result??x}
function typ(t){t=s(t).toLowerCase();if(['kv','kv_namespace','kv_namespaces'].includes(t))return'kv_namespace';if(['d1','d1_database','d1_databases'].includes(t))return'd1';if(['r2','r2_bucket','r2_buckets'].includes(t))return'r2_bucket';if(['service','services','service_binding'].includes(t))return'service';if(['var','vars','plain_text','text'].includes(t))return'plain_text';if(['secret','secrets','secret_text'].includes(t))return'secret_text';if(['workers_ai','ai'].includes(t))return'ai';if(['vectorize','vectorize_index'].includes(t))return'vectorize';return t||'unknown'}
function item(type,name,props={},src='unknown'){type=typ(type);name=s(name);return{key:type+':'+name,type,name,source:src,...props}}
function add(out,type,name,props={},src){if(name)out.push(item(type,name,Object.fromEntries(Object.entries(props).filter(([_,v])=>v!==undefined&&v!=='')),src))}
function repoBindings(j,secrets=[]){let out=[];j=j||{};for(const x of A(j.kv_namespaces))add(out,'kv_namespace',x.binding,{namespace_id:x.id,preview_id:x.preview_id},'wrangler');for(const x of A(j.d1_databases))add(out,'d1',x.binding,{database_id:x.database_id,database_name:x.database_name},'wrangler');for(const x of A(j.r2_buckets))add(out,'r2_bucket',x.binding,{bucket_name:x.bucket_name,preview_bucket_name:x.preview_bucket_name},'wrangler');for(const x of A(j.services))add(out,'service',x.binding||x.name,{service:x.service,environment:x.environment},'wrangler');for(const x of A(j.vectorize))add(out,'vectorize',x.binding,{index_name:x.index_name},'wrangler');for(const x of A(j.unsafe&&j.unsafe.bindings))add(out,x.type||'unsafe',x.name||x.binding,x,'wrangler');if(j.ai&&j.ai.binding)add(out,'ai',j.ai.binding,{binding:j.ai.binding},'wrangler');if(O(j.vars))for(const k of Object.keys(j.vars))add(out,'plain_text',k,{text:'present_in_wrangler'},'wrangler');for(const k of secrets)add(out,'secret_text',k,{expected:true},'expected');return out.sort((a,b)=>a.key.localeCompare(b.key))}
function liveBindings(r,secrets=[]){let out=[];r=r&&r.result?r.result:r||{};for(const b of A(r.bindings)){let type=typ(b.type),name=b.name||b.binding,props={};if(type==='d1')props={database_id:b.id||b.database_id,database_name:b.database_name};else if(type==='kv_namespace')props={namespace_id:b.namespace_id||b.id};else if(type==='r2_bucket')props={bucket_name:b.bucket_name||b.name};else if(type==='service')props={service:b.service,environment:b.environment};else if(type==='ai')props={binding:name};else if(type==='secret_text')props={secret_present:true};else if(type==='plain_text')props={text:'present_live'};else props={id:b.id,namespace_id:b.namespace_id,bucket_name:b.bucket_name,service:b.service,environment:b.environment,index_name:b.index_name};add(out,type,name,props,'cloudflare_live')}for(const k of secrets)if(!out.find(x=>x.type==='secret_text'&&x.name===k))add(out,'secret_text',k,{expected:true,not_confirmed:true},'expected');return out.sort((a,b)=>a.key.localeCompare(b.key))}
function val(v){if(v===undefined)return undefined;if(v===null||typeof v!=='object')return v;if(Array.isArray(v))return v.map(val);let o={};for(const k of ['id','binding','database_id','database_name','namespace_id','bucket_name','service','environment','index_name','text','secret_present','expected'])if(v[k]!==undefined)o[k]=v[k];return o}
function diff(a,b){let ks=new Set([...Object.keys(a),...Object.keys(b)].filter(k=>!['key','type','name','source'].includes(k))),d=[];for(const k of ks){let av=val(a[k]),bv=val(b[k]);if(JSON.stringify(av)!==JSON.stringify(bv))d.push({field:k,repo:av,live:bv})}return d}
function cmp(r,l){let R=new Map(r.map(x=>[x.key,x])),L=new Map(l.map(x=>[x.key,x])),missing=[],extra=[],changed=[],matches=[];for(const[k,v]of R){let w=L.get(k);if(!w)missing.push(v);else{let d=diff(v,w);d.length?changed.push({key:k,type:v.type,name:v.name,differences:d,repo:v,live:w}):matches.push({key:k,type:v.type,name:v.name})}}for(const[k,v]of L)if(!R.has(k))extra.push(v);let by_type={};for(const x of [...missing,...extra,...changed.map(x=>({type:x.type}))])by_type[x.type]=(by_type[x.type]||0)+1;return{severity:missing.length||changed.length?'fail':extra.length?'warn':'pass',summary:{repo_count:r.length,live_count:l.length,missing_count:missing.length,extra_count:extra.length,changed_count:changed.length,match_count:matches.length,issue_count:missing.length+extra.length+changed.length,issues_by_type:by_type},missing,extra,changed,matches}}
async function readRepo(e,a={}){let o=own(e,a),r=repo(e,a),ref=s(a.ref||a.branch||'main'),path=wp(e,a),f=await gh(e,`/repos/${encodeURIComponent(o)}/${encodeURIComponent(r)}/contents/${ep(path)}`,{ref}),text=dec(f.content),j,parse_error=null;try{j=jsonc(text)}catch(err){parse_error=String(err.message||err)}let bs=j?repoBindings(j,csv(a.expected_secret_names||e.EXPECTED_SECRET_NAMES)):[];return{ok:!parse_error,owner:o,repo:r,ref,path,sha:f.sha,size:f.size,parse_error,bindings:bs,binding_count:bs.length,wrangler:a.include_raw?j:undefined}}
async function live(e,a={}){let sc=script(e,a),r=await cf(e,a,'GET',`/accounts/{account_id}/workers/scripts/${encodeURIComponent(sc)}/settings`),bs=liveBindings(r,csv(a.expected_secret_names||e.EXPECTED_SECRET_NAMES));return{ok:true,account_id:acct(e,a),script_name:sc,compatibility_date:r.compatibility_date||null,compatibility_flags:r.compatibility_flags||[],bindings:bs,binding_count:bs.length,raw:a.include_raw?r:undefined}}
async function secrets(e,a={}){let sc=script(e,a),r=await cf(e,a,'GET',`/accounts/{account_id}/workers/scripts/${encodeURIComponent(sc)}/secrets`,{per_page:100}),arr=A(r).map(x=>({name:x.name,type:typ(x.type||'secret_text'),created_on:x.created_on||null,updated_on:x.updated_on||null}));return{ok:true,account_id:acct(e,a),script_name:sc,count:arr.length,secrets:arr}}
async function compare(e,a={}){let rr,lv,sec=null;try{rr=await readRepo(e,a)}catch(err){rr={ok:false,error:String(err.message||err)}}try{lv=await live(e,a)}catch(err){lv={ok:false,error:String(err.message||err)}}if(a.include_secrets!==false)try{sec=await secrets(e,a)}catch(err){sec={ok:false,error:String(err.message||err)}}let liveItems=A(lv.bindings);if(sec&&sec.ok)for(const x of sec.secrets)if(!liveItems.find(y=>y.type==='secret_text'&&y.name===x.name))liveItems.push(item('secret_text',x.name,{secret_present:true},'cloudflare_live_secrets'));let c=rr.ok&&lv.ok?cmp(rr.bindings,liveItems):null;return{ok:!!c,script_name:script(e,a),repo_wrangler:rr.ok?{owner:rr.owner,repo:rr.repo,ref:rr.ref,path:rr.path,sha:rr.sha,binding_count:rr.binding_count,bindings:rr.bindings}:rr,live_settings:lv.ok?{account_id:lv.account_id,script_name:lv.script_name,compatibility_date:lv.compatibility_date,binding_count:liveItems.length,bindings:liveItems}:lv,secrets:sec,comparison:c}}
function answer(x){if(!x.ok)return`Binding audit could not complete. Repo ok=${!!(x.repo_wrangler&&x.repo_wrangler.bindings)} live ok=${!!(x.live_settings&&x.live_settings.bindings)}. ${x.live_settings&&x.live_settings.error?x.live_settings.error:''}`;let c=x.comparison,s=c.summary,out=`Binding drift audit for ${x.script_name}: ${c.severity.toUpperCase()}. Repo=${s.repo_count}, live=${s.live_count}, missing=${s.missing_count}, extra=${s.extra_count}, changed=${s.changed_count}.`;if(c.missing.length)out+=' Missing live: '+c.missing.map(x=>`${x.type}:${x.name}`).join(', ')+'.';if(c.changed.length)out+=' Changed: '+c.changed.map(x=>`${x.type}:${x.name}`).join(', ')+'.';if(c.extra.length)out+=' Extra live: '+c.extra.map(x=>`${x.type}:${x.name}`).join(', ')+'.';return out}
async function investigate(e,a={}){let ev=await compare(e,a);return{ok:ev.ok,flow:'binding_drift_investigation',answer:answer(ev),evidence:a.include_raw?ev:{script_name:ev.script_name,repo_wrangler:ev.repo_wrangler&&ev.repo_wrangler.bindings?{owner:ev.repo_wrangler.owner,repo:ev.repo_wrangler.repo,ref:ev.repo_wrangler.ref,path:ev.repo_wrangler.path,sha:ev.repo_wrangler.sha,binding_count:ev.repo_wrangler.binding_count}:ev.repo_wrangler,live_settings:ev.live_settings&&ev.live_settings.bindings?{account_id:ev.live_settings.account_id,script_name:ev.live_settings.script_name,compatibility_date:ev.live_settings.compatibility_date,binding_count:ev.live_settings.binding_count}:ev.live_settings,secrets:ev.secrets&&ev.secrets.ok?{count:ev.secrets.count,names:ev.secrets.secrets.map(x=>x.name)}:ev.secrets,comparison:ev.comparison}}}
function status(e){return{ok:true,worker:W,deployed_as:e.WORKER_NAME||null,version:V,mode:'read_only_binding_investigator',bindings:{AI:!!e.AI,WORKER_NAME:!!e.WORKER_NAME,CLOUDFLARE_ACCOUNT_ID:!!acct(e,{}),CLOUDFLARE_API_TOKEN:!!cftok(e),GITHUB_TOKEN:!!ghtok(e),EXPECTED_SECRET_NAMES:!!e.EXPECTED_SECRET_NAMES},defaults:{owner:e.DEFAULT_OWNER||'nothinginfinity',repo:e.DEFAULT_REPO||'afo-visual-browser-subagent-mcp',script_name:e.DEFAULT_SCRIPT_NAME||'afo-cloudflare-deploy-investigator-mcp',wrangler_path:e.DEFAULT_WRANGLER_PATH||'subagents/cloudflare-deploy-investigator/wrangler.jsonc'},tools:['subagent_status','read_repo_wrangler','get_live_worker_bindings','list_live_worker_secrets','compare_bindings','investigate_binding_drift']}}
const schema=[
{name:'subagent_status',description:'Health check for the read-only Binding Investigator.',inputSchema:{type:'object',properties:{},required:[]}},
{name:'read_repo_wrangler',description:'Read and normalize a repo wrangler JSON/JSONC config. Includes D1, KV, R2, AI, services, vars, and expected secret names.',inputSchema:{type:'object',properties:{owner:{type:'string'},repo:{type:'string'},ref:{type:'string'},branch:{type:'string'},wrangler_path:{type:'string'},path:{type:'string'},config_path:{type:'string'},expected_secret_names:{type:'string'},include_raw:{type:'boolean'}},required:[]}},
{name:'get_live_worker_bindings',description:'Read live Cloudflare Worker settings and normalize binding names/types. Does not mutate anything.',inputSchema:{type:'object',properties:{account_id:{type:'string'},script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'},expected_secret_names:{type:'string'},include_raw:{type:'boolean'}},required:[]}},
{name:'list_live_worker_secrets',description:'List live Worker secret binding names only. It never reads secret values.',inputSchema:{type:'object',properties:{account_id:{type:'string'},script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'}},required:[]}},
{name:'compare_bindings',description:'Compare repo wrangler bindings against live Cloudflare Worker settings and report missing, extra, and changed bindings.',inputSchema:{type:'object',properties:{account_id:{type:'string'},script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'},owner:{type:'string'},repo:{type:'string'},ref:{type:'string'},branch:{type:'string'},wrangler_path:{type:'string'},path:{type:'string'},config_path:{type:'string'},expected_secret_names:{type:'string'},include_secrets:{type:'boolean'}},required:[]}},
{name:'investigate_binding_drift',description:'ONE-CALL binding drift investigation across repo wrangler config, live Worker settings, and secret binding name metadata.',inputSchema:{type:'object',properties:{account_id:{type:'string'},script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'},owner:{type:'string'},repo:{type:'string'},ref:{type:'string'},branch:{type:'string'},wrangler_path:{type:'string'},path:{type:'string'},config_path:{type:'string'},expected_secret_names:{type:'string'},include_secrets:{type:'boolean'},include_raw:{type:'boolean'}},required:[]}}
];
async function run(e,n,a={}){if(n==='subagent_status')return status(e);if(n==='read_repo_wrangler')return readRepo(e,a);if(n==='get_live_worker_bindings')return live(e,a);if(n==='list_live_worker_secrets')return secrets(e,a);if(n==='compare_bindings')return compare(e,a);if(n==='investigate_binding_drift')return investigate(e,a);throw Error('Unknown tool: '+n)}
async function mcp(req,e){const r=await B(req),id=r.id==null?null:r.id;try{if(r.method==='initialize')return J({jsonrpc:'2.0',id,result:{protocolVersion:'2024-11-05',capabilities:{tools:{}},serverInfo:{name:W,version:V}}});if(r.method==='notifications/initialized')return new Response(null,{status:204,headers:C});if(r.method==='ping')return J({jsonrpc:'2.0',id,result:{}});if(r.method==='tools/list')return J({jsonrpc:'2.0',id,result:{tools:schema}});if(r.method==='tools/call'){let result;try{result=await run(e,r.params&&r.params.name,r.params&&r.params.arguments||{})}catch(err){result={ok:false,error:String(err.message||err)}}return J({jsonrpc:'2.0',id,result:{content:[{type:'text',text:JSON.stringify(result,null,2)}],isError:result&&result.ok===false}})}return J({jsonrpc:'2.0',id,error:{code:-32601,message:'Method not found'}})}catch(err){return J({jsonrpc:'2.0',id,error:{code:-32603,message:String(err.message||err)}})}}
export default{async fetch(req,e){let u=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:C});try{if(u.pathname==='/'||u.pathname==='/status'||u.pathname==='/health')return J(status(e));if(u.pathname==='/tools')return J({ok:true,tools:schema});if(u.pathname==='/mcp')return mcp(req,e);if(req.method==='POST'&&u.pathname==='/call'){let b=await B(req);try{return J(await run(e,b.name,b.arguments||{}))}catch(err){return J({ok:false,error:String(err.message||err)},200)}}return J({ok:false,error:'not_found',worker:W},404)}catch(err){return J({ok:false,error:String(err.message||err),worker:W},500)}}};