const V='0.1.1',W='afo-route-dns-investigator-mcp',CF='https://api.cloudflare.com/client/v4';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization, Mcp-Session-Id'};
const s=x=>String(x??'').trim(), A=x=>Array.isArray(x)?x:[], O=x=>x&&typeof x==='object'&&!Array.isArray(x), n=(x,d=100)=>{x=Number(x);return Number.isFinite(x)?x:d};
function J(x,st=200){return new Response(JSON.stringify(x,null,2),{status:st,headers:{...C,'content-type':'application/json;charset=utf-8','cache-control':'no-store'}})}
async function B(r){try{return await r.json()}catch{return{}}}
function acct(e,a={}){return s(a.account_id||e.CLOUDFLARE_ACCOUNT_ID||e.CF_ACCOUNT_ID||e.ACCOUNT_ID)}
function tok(e){return s(e.CLOUDFLARE_API_TOKEN||e.CF_API_TOKEN||e.CLOUDFLARE_TOKEN)}
function sc(e,a={}){return s(a.script_name||a.worker||a.worker_name||e.DEFAULT_SCRIPT_NAME||'afo-binding-investigator-mcp')}
function sub(e){return s(e.ACCOUNT_SUBDOMAIN||e.CF_ACCOUNT_SUBDOMAIN||'jaredtechfit')}
function q(o={}){const u=new URLSearchParams();for(const[k,v]of Object.entries(o))if(v!==undefined&&v!==null&&v!=='')u.set(k,String(v));return u.toString()?'?'+u.toString():''}
async function cf(e,a,m,p,qq){let t=tok(e),id=acct(e,a);if(!t)throw Error('Cloudflare API token is required as Worker secret.');if(p.includes('{account_id}')&&!id)throw Error('Cloudflare account_id is required.');let url=CF+p.replaceAll('{account_id}',encodeURIComponent(id))+q(qq);const r=await fetch(url,{method:m,headers:{authorization:'Bearer '+t,accept:'application/json'}}),txt=await r.text();let x;try{x=JSON.parse(txt)}catch{x={raw:txt}}if(!r.ok||x.success===false)throw Error(`Cloudflare ${m} ${p} -> ${r.status}: ${JSON.stringify(x.errors||x).slice(0,300)}`);return x.result??x}
async function cft(e,a,label,m,p,qq){try{return{ok:true,label,result:await cf(e,a,m,p,qq)}}catch(err){return{ok:false,label,error:String(err.message||err)}}}
function hostFrom(u){u=s(u);if(!u)return'';try{return new URL(u.startsWith('http')?u:'https://'+u).hostname.toLowerCase()}catch{return u.split('/')[0].toLowerCase()}}
function urlObj(u,p='/'){u=s(u||'');if(!u&&p)return null;try{let x=new URL(u.startsWith('http')?u:'https://'+u);if((x.pathname==='/'||!x.pathname)&&p)x.pathname=p.startsWith('/')?p:'/'+p;return x}catch{return null}}
function esc(x){return x.replace(/[.+?^${}()|[\]\\]/g,'\\$&')}
function routeRe(pattern){let p=s(pattern).toLowerCase();if(!p)return/^$/;p=p.replace(/^https?:\/\//,'');let r='^'+p.split('*').map(esc).join('.*')+'$';return new RegExp(r)}
function routeHost(pattern){return s(pattern).replace(/^https?:\/\//,'').split('/')[0].replace(/\*/g,'').toLowerCase()}
function matchRoute(pattern,url){let u=urlObj(url)||null,txt=u?(u.hostname+u.pathname).toLowerCase():s(url).toLowerCase();return routeRe(pattern).test(txt)}
function scoreRoute(pattern){return s(pattern).replace(/\*/g,'').length}
function redir(txt,max=5000){txt=String(txt||'');return txt.length<=max?{text:txt,total_chars:txt.length,truncated:false}:{text:txt.slice(0,1800)+'\n--- truncated ---\n'+txt.slice(-2500),total_chars:txt.length,truncated:true}}
function normDns(x){return{id:x.id,type:x.type,name:x.name,content:x.content,proxied:x.proxied,ttl:x.ttl,comment:x.comment,tags:x.tags,created_on:x.created_on,modified_on:x.modified_on}}
function normRoute(x){return{id:x.id,pattern:x.pattern,script:x.script,zone_name:x.zone_name,enabled:x.enabled!==false}}
function normDomain(x){return{id:x.id,hostname:x.hostname,service:x.service||x.script_name,environment:x.environment,zone_id:x.zone_id,zone_name:x.zone_name,created_on:x.created_on,modified_on:x.modified_on}}
function bval(x,d=false){if(x===undefined||x===null||x==='')return d;if(typeof x==='boolean')return x;let v=String(x).toLowerCase();if(['1','true','yes','on'].includes(v))return true;if(['0','false','no','off'].includes(v))return false;return d}
function explicitZone(e,a={}){return!!(a.zone_id||a.zone_name||a.domain||e.CF_ZONE_ID||e.DEFAULT_ZONE_ID)}
function scanAll(e,a={}){return bval(a.scan_all_zones??a.account_wide,e.DEFAULT_SCAN_ALL_ZONES===undefined?true:bval(e.DEFAULT_SCAN_ALL_ZONES,true))}
function normZone(x){return{id:x.id,name:x.name,status:x.status,type:x.type,account:x.account?{id:x.account.id,name:x.account.name}:undefined,created_on:x.created_on,modified_on:x.modified_on}}
function zoneHit(z,h){let n=s(z&&z.name).toLowerCase();return!!(n&&h&&(h===n||h.endsWith('.'+n)))}
function isWorkersDev(h,e){return s(h).endsWith('.workers.dev')||s(h).endsWith('.'+sub(e)+'.workers.dev')}
async function listZones(e,a={}){let id=acct(e,a),name=s(a.name||a.zone_name||a.domain),p={name:name||undefined,status:s(a.status)||undefined,per_page:Math.min(Math.max(n(a.limit||a.max_zones,100),1),500)};if(id)p['account.id']=id;let r=await cf(e,a,'GET','/zones',p),zones=A(r).map(normZone);return{ok:true,account_id:id||null,count:zones.length,zones}}
async function resolveZone(e,a={}){let zid=s(a.zone_id||e.CF_ZONE_ID||e.DEFAULT_ZONE_ID),zn=s(a.zone_name||a.domain||e.DEFAULT_ZONE_NAME);if(zid)return{ok:true,zone_id:zid,zone_name:zn||null,source:'provided'};if(!zn)return{ok:false,error:'zone_id or zone_name/domain is required for zone-scoped checks'};let r=await listZones(e,{...a,name:zn,limit:50});let z=A(r.zones).find(x=>x.name===zn)||A(r.zones)[0];return z?{ok:true,zone_id:z.id,zone_name:z.name,status:z.status,source:'cloudflare_zones'}:{ok:false,error:'zone not found: '+zn}}
async function zonesForScan(e,a={}){let h=hostFrom(a.url||a.live_url||a.hostname||a.domain||''),all=scanAll(e,a);if(explicitZone(e,a)||!all){let z=await resolveZone(e,a);return z.ok?{ok:true,mode:explicitZone(e,a)?'explicit_zone':'default_zone',zones:[{id:z.zone_id,name:z.zone_name}],host:h}:z}let l=await listZones(e,{...a,limit:Math.min(Math.max(n(a.max_zones,100),1),200)}),zones=A(l.zones);if(h&&!isWorkersDev(h,e)){let m=zones.filter(z=>zoneHit(z,h));if(m.length)zones=m;else if(e.DEFAULT_ZONE_NAME){let f=zones.filter(z=>z.name===e.DEFAULT_ZONE_NAME);if(f.length)zones=f}}return{ok:true,mode:'account_wide',zones,host:h,all_zone_count:l.count}}
async function listDns(e,a={}){let name=s(a.hostname||a.name||a.url&&hostFrom(a.url)||''),type=s(a.type),per=Math.min(Math.max(n(a.limit,100),1),500);if(explicitZone(e,a)||!scanAll(e,a)){let z=await resolveZone(e,a);if(!z.ok)return z;let r=await cf(e,a,'GET',`/zones/${encodeURIComponent(z.zone_id)}/dns_records`,{name:name||undefined,type:type||undefined,per_page:per});let out=A(r).map(x=>({...normDns(x),zone_id:z.zone_id,zone_name:z.zone_name}));return{ok:true,mode:'zone_scoped',zone:z,count:out.length,records:out}}let zs=await zonesForScan(e,a);if(!zs.ok)return zs;let out=[],failures=[];for(const z of A(zs.zones)){let r=await cft(e,a,'dns:'+z.name,'GET',`/zones/${encodeURIComponent(z.id)}/dns_records`,{name:name||undefined,type:type||undefined,per_page:per});if(r.ok)out.push(...A(r.result).map(x=>({...normDns(x),zone_id:z.id,zone_name:z.name})));else failures.push({zone:z,error:r.error})}return{ok:true,mode:'account_wide',zones_scanned:A(zs.zones).length,count:out.length,records:out,failures}}
async function listRoutes(e,a={}){let target=sc(e,a),url=s(a.url||a.live_url||a.hostname),per=Math.min(Math.max(n(a.limit,100),1),500);if(explicitZone(e,a)||!scanAll(e,a)){let z=await resolveZone(e,a);if(!z.ok)return z;let r=await cf(e,a,'GET',`/zones/${encodeURIComponent(z.zone_id)}/workers/routes`,{per_page:per});let routes=A(r).map(x=>({...normRoute(x),zone_id:z.zone_id,zone_name:z.zone_name})),all=routes;if(a.only_target!==false&&target)routes=routes.filter(x=>x.script===target||!a.script_name&&!a.worker&&!a.worker_name);let matched=url?all.filter(x=>matchRoute(x.pattern,url)).sort((a,b)=>scoreRoute(b.pattern)-scoreRoute(a.pattern)):[];return{ok:true,mode:'zone_scoped',zone:z,script_name:target,count:routes.length,routes,matched_count:matched.length,matched_routes:matched}}let zs=await zonesForScan(e,a);if(!zs.ok)return zs;let all=[],failures=[];for(const z of A(zs.zones)){let r=await cft(e,a,'routes:'+z.name,'GET',`/zones/${encodeURIComponent(z.id)}/workers/routes`,{per_page:per});if(r.ok)all.push(...A(r.result).map(x=>({...normRoute(x),zone_id:z.id,zone_name:z.name})));else failures.push({zone:z,error:r.error})}let routes=all;if(a.only_target!==false&&target)routes=routes.filter(x=>x.script===target||!a.script_name&&!a.worker&&!a.worker_name);let matched=url?all.filter(x=>matchRoute(x.pattern,url)).sort((a,b)=>scoreRoute(b.pattern)-scoreRoute(a.pattern)):[];return{ok:true,mode:'account_wide',script_name:target,zones_scanned:A(zs.zones).length,all_route_count:all.length,count:routes.length,routes,matched_count:matched.length,matched_routes:matched,failures}}
async function customDomains(e,a={}){let target=sc(e,a),r=await cf(e,a,'GET','/accounts/{account_id}/workers/domains/records',{per_page:Math.min(Math.max(n(a.limit,100),1),500)});let arr=A(r).map(normDomain),host=hostFrom(a.hostname||a.url||'');if(target&&a.only_target!==false)arr=arr.filter(x=>x.service===target);if(host)arr=arr.filter(x=>x.hostname===host||x.hostname.endsWith('.'+host)||host.endsWith('.'+x.hostname));return{ok:true,account_id:acct(e,a),script_name:target,count:arr.length,custom_domains:arr}}
async function workersDev(e,a={}){let target=sc(e,a),r=await cft(e,a,'subdomain','GET',`/accounts/{account_id}/workers/scripts/${encodeURIComponent(target)}/subdomain`);let sd=sub(e),raw=r.ok?r.result:null;let enabled=!!(raw&&(raw.enabled===true||raw.previews_enabled===true||raw.subdomain));let acc=s(raw&&(raw.subdomain||raw.account_subdomain)||sd);return{ok:true,script_name:target,workers_dev_url:acc?`https://${target}.${acc}.workers.dev`:null,enabled,previews_enabled:raw&&raw.previews_enabled,attempt:r}}
async function smoke(e,a={}){let target=sc(e,a),w=await workersDev(e,a).catch(()=>({workers_dev_url:`https://${target}.${sub(e)}.workers.dev`}));let u=urlObj(s(a.url||a.live_url||a.workers_dev_url||w.workers_dev_url),s(a.path||a.status_path||'/status'));if(!u)throw Error('url/live_url/workers_dev_url is required');let h={accept:'application/json,text/plain,*/*','user-agent':W+'/'+V};if(a.host_header)h.host=s(a.host_header);let t=Date.now(),r=await fetch(u.toString(),{method:s(a.method||'GET'),headers:h,redirect:'manual'}),ct=r.headers.get('content-type')||'',txt=await r.text(),json=null;try{if(ct.includes('json'))json=JSON.parse(txt)}catch{}let body=json||redir(txt,Math.min(Math.max(n(a.max_chars,5000),500),20000));let detected={worker:null,version:null};if(json){detected.worker=s(json.worker||json.name||json.deployed_as||json.service||'')||null;detected.version=s(json.version||json.VERSION||'')||null}else{let m=txt.match(/afo-[a-z0-9-]+-mcp/);if(m)detected.worker=m[0];let v=txt.match(/v?\d+\.\d+(?:\.\d+)?/);if(v)detected.version=v[0]}return{ok:true,url:u.toString(),intended_worker:target,status:r.status,location:r.headers.get('location'),content_type:ct,elapsed_ms:Date.now()-t,detected,appears_to_hit_intended:detected.worker?detected.worker===target:null,body}}
async function analyze(e,a={}){let target=sc(e,a),url=s(a.url||a.live_url||a.hostname||''),host=hostFrom(url),res={ok:true,script_name:target,input:{url,host},zone:null,dns:null,routes:null,custom_domains:null,workers_dev:null,smoke:null,conflicts:[],matches:[],warnings:[]};let z=await resolveZone(e,a).catch(err=>({ok:false,error:String(err.message||err)}));res.zone=z;if(z.ok){res.dns=await listDns(e,{...a,hostname:host||a.hostname,only_target:false}).catch(err=>({ok:false,error:String(err.message||err)}));let allRoutes=await listRoutes(e,{...a,only_target:false,url:url||host}).catch(err=>({ok:false,error:String(err.message||err)}));res.routes=allRoutes;if(allRoutes.ok){let m=A(allRoutes.matched_routes).sort((a,b)=>scoreRoute(b.pattern)-scoreRoute(a.pattern));res.matches.push(...m.map(x=>({kind:'worker_route',...x,specificity:scoreRoute(x.pattern),intended:x.script===target})));let top=m[0];if(top&&top.script!==target)res.conflicts.push({kind:'route_conflict',message:'Most specific matching route points at a different Worker',intended_worker:target,matched_worker:top.script,pattern:top.pattern});let dup=m.filter(x=>x.script!==target);if(dup.length)res.warnings.push({kind:'other_matching_routes',routes:dup})}}else res.warnings.push({kind:'zone_unresolved',error:z.error});res.custom_domains=await customDomains(e,{...a,only_target:false,url:url||host}).catch(err=>({ok:false,error:String(err.message||err)}));if(res.custom_domains&&res.custom_domains.ok){let arr=A(res.custom_domains.custom_domains),exact=arr.filter(x=>x.hostname===host);res.matches.push(...exact.map(x=>({kind:'custom_domain',...x,intended:x.service===target})));for(const x of exact)if(x.service!==target)res.conflicts.push({kind:'custom_domain_conflict',message:'Hostname custom domain points at a different Worker',intended_worker:target,matched_worker:x.service,hostname:x.hostname})}res.workers_dev=await workersDev(e,a).catch(err=>({ok:false,error:String(err.message||err)}));if(a.smoke!==false)res.smoke=await smoke(e,a).catch(err=>({ok:false,error:String(err.message||err)}));if(res.smoke&&res.smoke.ok&&res.smoke.appears_to_hit_intended===false)res.conflicts.push({kind:'live_behavior_mismatch',message:'Smoke check detected a different Worker marker',intended_worker:target,detected_worker:res.smoke.detected.worker,url:res.smoke.url});if(res.dns&&res.dns.ok){for(const r of A(res.dns.records)){if(host&&r.name===host&&r.type==='CNAME'&&!String(r.content||'').includes('workers.dev')&&!String(r.content||'').includes('worker.dev'))res.warnings.push({kind:'dns_cname_not_workers_dev',record:r});if(host&&r.name===host&&r.proxied===false)res.warnings.push({kind:'dns_not_proxied',record:r})}}res.severity=res.conflicts.length?'fail':res.warnings.length?'warn':'pass';return res}
function summary(x){if(!x.ok)return'Route/DNS investigation failed.';let out=`Route/DNS investigation for ${x.script_name}: ${x.severity.toUpperCase()}.`;if(x.input.host)out+=` Host=${x.input.host}.`;if(x.zone&&x.zone.ok)out+=` Zone=${x.zone.zone_name||x.zone.zone_id}.`;if(x.dns&&x.dns.ok)out+=` DNS records=${x.dns.count}.`;if(x.routes&&x.routes.ok)out+=` Routes=${x.routes.count}, matched=${x.routes.matched_count}.`;if(x.custom_domains&&x.custom_domains.ok)out+=` Custom domains=${x.custom_domains.count}.`;if(x.workers_dev&&x.workers_dev.ok)out+=` workers.dev=${x.workers_dev.workers_dev_url||'unknown'}.`;if(x.smoke&&x.smoke.ok)out+=` Smoke HTTP ${x.smoke.status}${x.smoke.detected.worker?`, detected ${x.smoke.detected.worker}`:''}.`;if(x.conflicts.length)out+=' Conflicts: '+x.conflicts.map(c=>c.kind).join(', ')+'.';else if(x.warnings.length)out+=' Warnings: '+x.warnings.map(c=>c.kind).join(', ')+'.';else out+=' No conflicts found in gathered evidence.';return out}
async function investigate(e,a={}){let ev=await analyze(e,a);return{ok:true,flow:'route_dns_investigation',answer:summary(ev),evidence:a.include_raw?ev:{script_name:ev.script_name,severity:ev.severity,input:ev.input,zone:ev.zone,dns:ev.dns&&ev.dns.ok?{count:ev.dns.count,records:A(ev.dns.records).slice(0,20)}:ev.dns,routes:ev.routes&&ev.routes.ok?{count:ev.routes.count,matched_count:ev.routes.matched_count,matched_routes:ev.routes.matched_routes,routes:A(ev.routes.routes).slice(0,30)}:ev.routes,custom_domains:ev.custom_domains&&ev.custom_domains.ok?{count:ev.custom_domains.count,custom_domains:A(ev.custom_domains.custom_domains).slice(0,30)}:ev.custom_domains,workers_dev:ev.workers_dev,smoke:ev.smoke&&ev.smoke.ok?{url:ev.smoke.url,status:ev.smoke.status,detected:ev.smoke.detected,appears_to_hit_intended:ev.smoke.appears_to_hit_intended}:ev.smoke,conflicts:ev.conflicts,warnings:ev.warnings}}}
function status(e){return{ok:true,worker:W,deployed_as:e.WORKER_NAME||null,version:V,mode:'read_only_route_dns_investigator_account_wide',bindings:{AI:!!e.AI,WORKER_NAME:!!e.WORKER_NAME,CLOUDFLARE_ACCOUNT_ID:!!acct(e,{}),CLOUDFLARE_API_TOKEN:!!tok(e),CF_ZONE_ID:!!(e.CF_ZONE_ID||e.DEFAULT_ZONE_ID),DEFAULT_ZONE_NAME:!!e.DEFAULT_ZONE_NAME,ACCOUNT_SUBDOMAIN:!!(e.ACCOUNT_SUBDOMAIN||e.CF_ACCOUNT_SUBDOMAIN),DEFAULT_SCAN_ALL_ZONES:scanAll(e,{})},defaults:{script_name:e.DEFAULT_SCRIPT_NAME||'afo-binding-investigator-mcp',account_subdomain:sub(e),zone_name:e.DEFAULT_ZONE_NAME||null,scan_all_zones:scanAll(e,{})},tools:['subagent_status','list_account_zones','resolve_zone','list_dns_records','list_worker_routes','list_custom_domains','get_workers_dev_url','smoke_endpoint','analyze_route_conflicts','investigate_route_dns']}}
const tools=[
{name:'subagent_status',description:'Health check for the read-only Route / DNS Investigator.',inputSchema:{type:'object',properties:{},required:[]}},
{name:'list_account_zones',description:'List Cloudflare zones visible to the account token. Read-only account-wide discovery.',inputSchema:{type:'object',properties:{account_id:{type:'string'},name:{type:'string'},zone_name:{type:'string'},domain:{type:'string'},status:{type:'string'},limit:{type:'number'},max_zones:{type:'number'}},required:[]}},
{name:'resolve_zone',description:'Resolve a Cloudflare zone by zone_id or zone_name/domain. Read-only.',inputSchema:{type:'object',properties:{account_id:{type:'string'},zone_id:{type:'string'},zone_name:{type:'string'},domain:{type:'string'}},required:[]}},
{name:'list_dns_records',description:'List DNS records for a zone, optionally scoped to a hostname/type. Read-only.',inputSchema:{type:'object',properties:{account_id:{type:'string'},zone_id:{type:'string'},zone_name:{type:'string'},domain:{type:'string'},hostname:{type:'string'},name:{type:'string'},url:{type:'string'},type:{type:'string'},limit:{type:'number'}},required:[]}},
{name:'list_worker_routes',description:'List Worker routes for a zone and optionally identify routes matching a URL/hostname. Read-only.',inputSchema:{type:'object',properties:{account_id:{type:'string'},zone_id:{type:'string'},zone_name:{type:'string'},domain:{type:'string'},script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'},url:{type:'string'},live_url:{type:'string'},hostname:{type:'string'},only_target:{type:'boolean'},limit:{type:'number'}},required:[]}},
{name:'list_custom_domains',description:'List account Worker custom domains and filter by Worker or hostname. Read-only.',inputSchema:{type:'object',properties:{account_id:{type:'string'},script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'},url:{type:'string'},hostname:{type:'string'},only_target:{type:'boolean'},limit:{type:'number'}},required:[]}},
{name:'get_workers_dev_url',description:'Read workers.dev subdomain status and construct fallback workers.dev URL for a Worker. Read-only.',inputSchema:{type:'object',properties:{account_id:{type:'string'},script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'}},required:[]}},
{name:'smoke_endpoint',description:'HTTP smoke check an endpoint or workers.dev fallback and detect Worker/version markers. Read-only.',inputSchema:{type:'object',properties:{script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'},url:{type:'string'},live_url:{type:'string'},workers_dev_url:{type:'string'},path:{type:'string'},status_path:{type:'string'},host_header:{type:'string'},method:{type:'string'},max_chars:{type:'number'}},required:[]}},
{name:'analyze_route_conflicts',description:'Analyze DNS, Worker routes, custom domains, workers.dev fallback, route conflicts, and live smoke behavior. Read-only.',inputSchema:{type:'object',properties:{account_id:{type:'string'},zone_id:{type:'string'},zone_name:{type:'string'},domain:{type:'string'},script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'},url:{type:'string'},live_url:{type:'string'},hostname:{type:'string'},path:{type:'string'},status_path:{type:'string'},smoke:{type:'boolean'},include_raw:{type:'boolean'}},required:[]}},
{name:'investigate_route_dns',description:'ONE-CALL Route/DNS investigation: zones, DNS, routes, custom domains, workers.dev fallback, conflicts, and endpoint smoke check. Read-only.',inputSchema:{type:'object',properties:{account_id:{type:'string'},zone_id:{type:'string'},zone_name:{type:'string'},domain:{type:'string'},script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'},url:{type:'string'},live_url:{type:'string'},hostname:{type:'string'},path:{type:'string'},status_path:{type:'string'},smoke:{type:'boolean'},include_raw:{type:'boolean'}},required:[]}}
];
async function run(e,nm,a={}){if(nm==='subagent_status')return status(e);if(nm==='list_account_zones')return listZones(e,a);if(nm==='resolve_zone')return resolveZone(e,a);if(nm==='list_dns_records')return listDns(e,a);if(nm==='list_worker_routes')return listRoutes(e,a);if(nm==='list_custom_domains')return customDomains(e,a);if(nm==='get_workers_dev_url')return workersDev(e,a);if(nm==='smoke_endpoint')return smoke(e,a);if(nm==='analyze_route_conflicts')return analyze(e,a);if(nm==='investigate_route_dns')return investigate(e,a);throw Error('Unknown tool: '+nm)}
async function mcp(req,e){const r=await B(req),id=r.id==null?null:r.id;try{if(r.method==='initialize')return J({jsonrpc:'2.0',id,result:{protocolVersion:'2024-11-05',capabilities:{tools:{}},serverInfo:{name:W,version:V}}});if(r.method==='notifications/initialized')return new Response(null,{status:204,headers:C});if(r.method==='ping')return J({jsonrpc:'2.0',id,result:{}});if(r.method==='tools/list')return J({jsonrpc:'2.0',id,result:{tools}});if(r.method==='tools/call'){let result;try{result=await run(e,r.params&&r.params.name,r.params&&r.params.arguments||{})}catch(err){result={ok:false,error:String(err.message||err)}}return J({jsonrpc:'2.0',id,result:{content:[{type:'text',text:JSON.stringify(result,null,2)}],isError:result&&result.ok===false}})}return J({jsonrpc:'2.0',id,error:{code:-32601,message:'Method not found'}})}catch(err){return J({jsonrpc:'2.0',id,error:{code:-32603,message:String(err.message||err)}})}}
export default{async fetch(req,e){let u=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:C});try{if(u.pathname==='/'||u.pathname==='/status'||u.pathname==='/health')return J(status(e));if(u.pathname==='/tools')return J({ok:true,tools});if(u.pathname==='/mcp')return mcp(req,e);if(req.method==='POST'&&u.pathname==='/call'){let b=await B(req);try{return J(await run(e,b.name,b.arguments||{}))}catch(err){return J({ok:false,error:String(err.message||err)},200)}}return J({ok:false,error:'not_found',worker:W},404)}catch(err){return J({ok:false,error:String(err.message||err),worker:W},500)}}};