const VERSION='0.1.0';
const WORKER='afo-cloudflare-deploy-investigator-mcp';
const CF='https://api.cloudflare.com/client/v4';
const GH='https://api.github.com';
const MODEL='@cf/meta/llama-3.3-70b-instruct-fp8-fast';
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization, Mcp-Session-Id'};
const s=v=>String(v||'').trim(), A=v=>Array.isArray(v)?v:[], clamp=(v,d,min,max)=>{v=Number(v);return Number.isFinite(v)?Math.max(min,Math.min(max,v)):d};
function J(x,st=200){return new Response(JSON.stringify(x,null,2),{status:st,headers:{...CORS,'content-type':'application/json;charset=utf-8','cache-control':'no-store'}})}
async function B(r){try{return await r.json()}catch{return {}}}
function acct(env,a={}){return s(a.account_id||env.CLOUDFLARE_ACCOUNT_ID||env.CF_ACCOUNT_ID||env.ACCOUNT_ID)}
function cfTok(env){return s(env.CLOUDFLARE_API_TOKEN||env.CF_API_TOKEN||env.CLOUDFLARE_TOKEN)}
function ghTok(env){return s(env.GITHUB_TOKEN||env.GH_TOKEN)}
function script(env,a={}){return s(a.script_name||a.worker||a.worker_name||env.DEFAULT_SCRIPT_NAME||'afo-github-actions-investigator-mcp')}
function owner(env,a={}){return s(a.owner||env.DEFAULT_OWNER||'nothinginfinity')}
function repo(env,a={}){return s(a.repo||env.DEFAULT_REPO||'afo-visual-browser-subagent-mcp')}
function qs(o={}){const u=new URLSearchParams();for(const[k,v]of Object.entries(o))if(v!==undefined&&v!==null&&v!=='')u.set(k,String(v));const x=u.toString();return x?'?'+x:''}
function encPath(p){return s(p).split('/').map(encodeURIComponent).join('/')}
function ext(t,max=10000){t=String(t||'');if(t.length<=max)return{text:t,truncated:false,total_chars:t.length};const h=Math.floor(max*.35);return{text:t.slice(0,h)+'\n\n--- MIDDLE TRUNCATED ---\n\n'+t.slice(-(max-h)),truncated:true,total_chars:t.length}}
function ver(t){t=String(t||'');for(const p of [/const\s+VERSION\s*=\s*['"]([^'"]+)['"]/,/VERSION\s*[:=]\s*['"]([^'"]+)['"]/,/version\s*[:=]\s*['"]([^'"]+)['"]/i,/v\d+\.\d+(?:\.\d+)?/]){const m=t.match(p);if(m)return m[1]||m[0]}return null}
function wmark(t){const m=String(t||'').match(/const\s+WORKER\s*=\s*['"]([^'"]+)['"]/);return m?m[1]:null}
async function hash(t){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(t||'')));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function dec(b64){const raw=atob(String(b64||'').replace(/\n/g,''));const b=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)b[i]=raw.charCodeAt(i);return new TextDecoder().decode(b)}
function T(){const t0=Date.now(),st={};let k,ts;return{go(x){if(k)st[k]=(st[k]||0)+Date.now()-ts;k=x;ts=Date.now()},done(){if(k)st[k]=(st[k]||0)+Date.now()-ts;return{stages_ms:st,total_ms:Date.now()-t0}}}}
async function cf(env,a,method,path,q){const id=acct(env,a),tok=cfTok(env);if(!id)throw new Error('Cloudflare account_id is required. Set CLOUDFLARE_ACCOUNT_ID or pass account_id.');if(!tok)throw new Error('Cloudflare API token is required. Set CLOUDFLARE_API_TOKEN or CF_API_TOKEN as a Worker secret.');const r=await fetch(CF+path.replaceAll('{account_id}',encodeURIComponent(id))+qs(q),{method,headers:{authorization:`Bearer ${tok}`,accept:'application/json','content-type':'application/json'}});const ct=r.headers.get('content-type')||'',txt=await r.text();let data=txt;if(ct.includes('json'))try{data=JSON.parse(txt)}catch{data={raw:txt}}if(!r.ok||data&&data.success===false)throw new Error(`Cloudflare ${method} ${path} -> ${r.status}: ${JSON.stringify(data.errors||data).slice(0,420)}`);return{status:r.status,content_type:ct,data}}
async function cft(env,a,label,method,path,q){try{return{ok:true,label,...await cf(env,a,method,path,q)}}catch(e){return{ok:false,label,error:String(e.message||e)}}}
async function gh(env,path,q){const h={accept:'application/vnd.github+json','user-agent':`${WORKER}/${VERSION}`,'x-github-api-version':'2022-11-28'};const tok=ghTok(env);if(tok)h.authorization=`Bearer ${tok}`;const r=await fetch(GH+path+qs(q),{headers:h});const txt=await r.text();let data;try{data=JSON.parse(txt)}catch{data={raw:txt}}if(!r.ok)throw new Error(`GitHub GET ${path} -> ${r.status}: ${data.message||txt.slice(0,220)}`);return data}
function smallScript(x){return{id:x.id||x.script_name||x.name||null,name:x.script_name||x.id||x.name||null,created_on:x.created_on||x.created_at||null,modified_on:x.modified_on||x.updated_on||null,etag:x.etag||null,usage_model:x.usage_model||undefined}}
function bindings(x){const r=x&&x.result?x.result:x,bs=A(r&&r.bindings);return bs.map(b=>({name:b.name,type:b.type,namespace_id:b.namespace_id,id:b.id,bucket_name:b.bucket_name,service:b.service,environment:b.environment}))}
function settings(x){const r=x&&x.result?x.result:x;if(!r||typeof r!=='object')return r;return{compatibility_date:r.compatibility_date||null,compatibility_flags:r.compatibility_flags||[],usage_model:r.usage_model||null,placement:r.placement||undefined,bindings:bindings(r)}}
function subdomain(x,env,sc){const r=x&&x.result?x.result:x;const sub=s(r&&(r.subdomain||r.account_subdomain)||env.ACCOUNT_SUBDOMAIN||env.CF_ACCOUNT_SUBDOMAIN||'jaredtechfit');return{enabled:!!(r&&(r.enabled===true||r.previews_enabled===true||r.subdomain)),previews_enabled:r&&r.previews_enabled,account_subdomain:sub||null,workers_dev_url:sub?`https://${sc}.${sub}.workers.dev`:null,raw:r||null}}
async function listWorkers(env,a={}){const limit=clamp(a.limit,100,1,1000);const o=await cf(env,a,'GET','/accounts/{account_id}/workers/scripts',{per_page:Math.min(limit,1000)});let w=A(o.data&&o.data.result).map(smallScript);const q=s(a.query).toLowerCase();if(q)w=w.filter(x=>`${x.id} ${x.name}`.toLowerCase().includes(q));return{ok:true,account_id:acct(env,a),count:w.length,workers:w.slice(0,limit)}}
async function getWorkerSettings(env,a={}){const sc=script(env,a);const res=await Promise.all([cft(env,a,'settings','GET',`/accounts/{account_id}/workers/scripts/${encodeURIComponent(sc)}/settings`),cft(env,a,'script','GET',`/accounts/{account_id}/workers/scripts/${encodeURIComponent(sc)}`),cft(env,a,'subdomain','GET',`/accounts/{account_id}/workers/scripts/${encodeURIComponent(sc)}/subdomain`),cft(env,a,'usage_model','GET',`/accounts/{account_id}/workers/scripts/${encodeURIComponent(sc)}/usage-model`)]);const[set,meta,sub,use]=res;return{ok:true,account_id:acct(env,a),script_name:sc,script:meta.ok?smallScript(meta.data.result||meta.data):null,settings:set.ok?settings(set.data):null,subdomain:sub.ok?subdomain(sub.data,env,sc):null,usage_model:use.ok?(use.data.result||use.data):null,errors:res.filter(x=>!x.ok).map(x=>({label:x.label,error:x.error}))}}
async function getDeploymentHistory(env,a={}){const sc=script(env,a),limit=clamp(a.limit,10,1,50);const tries=[['deployments',`/accounts/{account_id}/workers/scripts/${encodeURIComponent(sc)}/deployments`],['versions',`/accounts/{account_id}/workers/scripts/${encodeURIComponent(sc)}/versions`]];const out=[];for(const[x,p]of tries)out.push(await cft(env,a,x,'GET',p,{per_page:limit}));const good=out.find(x=>x.ok);let items=[];if(good)items=A(good.data.result).slice(0,limit).map(d=>({id:d.id||d.deployment_id||null,number:d.number||null,created_on:d.created_on||d.created_at||null,source:d.source,annotations:d.annotations,versions:d.versions,metadata:d.metadata}));return{ok:true,account_id:acct(env,a),script_name:sc,source:good&&good.label,count:items.length,items,attempts:out.map(x=>({label:x.label,ok:x.ok,status:x.status||null,error:x.error||null}))}}
async function getScriptContent(env,a={}){const sc=script(env,a),max=clamp(a.max_chars,16000,1000,120000);for(const[label,path]of [['content_v2',`/accounts/{account_id}/workers/scripts/${encodeURIComponent(sc)}/content/v2`],['download_worker',`/accounts/{account_id}/workers/scripts/${encodeURIComponent(sc)}`]]){try{const o=await cf(env,a,'GET',path);const text=typeof o.data==='string'?o.data:JSON.stringify(o.data,null,2);return{ok:true,account_id:acct(env,a),script_name:sc,source:label,content_type:o.content_type,sha256:await hash(text),version_marker:ver(text),worker_marker:wmark(text),...ext(text,max)}}catch(e){}}return{ok:false,account_id:acct(env,a),script_name:sc,error:'Could not fetch script content with supported endpoints'}}
async function listRoutes(env,a={}){const sc=script(env,a),out={ok:true,account_id:acct(env,a),script_name:sc,routes:[],custom_domains:[],attempts:[]};const zid=s(a.zone_id||env.CF_ZONE_ID||env.DEFAULT_ZONE_ID);if(zid){const r=await cft(env,a,'zone_worker_routes','GET',`/zones/${encodeURIComponent(zid)}/workers/routes`,{per_page:100});out.attempts.push({label:r.label,ok:r.ok,status:r.status||null,error:r.error||null});if(r.ok)out.routes=A(r.data.result).filter(x=>!sc||x.script===sc).map(x=>({id:x.id,pattern:x.pattern,script:x.script,zone_name:x.zone_name,enabled:x.enabled}))}const d=await cft(env,a,'account_worker_domains','GET','/accounts/{account_id}/workers/domains/records',{per_page:100});out.attempts.push({label:d.label,ok:d.ok,status:d.status||null,error:d.error||null});if(d.ok)out.custom_domains=A(d.data.result).filter(x=>!sc||x.service===sc||x.script_name===sc).map(x=>({id:x.id,hostname:x.hostname,service:x.service||x.script_name,environment:x.environment,zone_id:x.zone_id,zone_name:x.zone_name}));out.count=out.routes.length+out.custom_domains.length;return out}
async function smokeLive(env,a={}){const sc=script(env,a);let u=s(a.workers_dev_url||a.live_url||a.url||`https://${sc}.${s(env.ACCOUNT_SUBDOMAIN||env.CF_ACCOUNT_SUBDOMAIN||'jaredtechfit')}.workers.dev`);const p=s(a.path||a.status_path||'/status')||'/status';const U=new URL(u.startsWith('http')?u:'https://'+u);if(U.pathname==='/'&&p)U.pathname=p.startsWith('/')?p:'/'+p;const t=Date.now();const r=await fetch(U.toString(),{method:s(a.method||'GET'),headers:{accept:'application/json,text/plain,*/*'}});const ct=r.headers.get('content-type')||'',txt=await r.text();let parsed=null;if(ct.includes('json'))try{parsed=JSON.parse(txt)}catch{}return{ok:true,url:U.toString(),status:r.status,content_type:ct,elapsed_ms:Date.now()-t,detected:{version:parsed&&(parsed.version||parsed.VERSION)||ver(txt),worker:parsed&&(parsed.worker||parsed.name||parsed.deployed_as)||wmark(txt)},body:parsed||ext(txt,clamp(a.max_chars,5000,500,30000))}}
async function getGithubSource(env,a={}){const o=owner(env,a),r=repo(env,a),ref=s(a.ref||a.branch||'main'),path=s(a.path||a.source_path||a.github_path||'subagents/github-actions-investigator/worker.js');const f=await gh(env,`/repos/${encodeURIComponent(o)}/${encodeURIComponent(r)}/contents/${encPath(path)}`,{ref});const text=dec(f.content||'');return{ok:true,owner:o,repo:r,ref,path,sha:f.sha,size:f.size,sha256:await hash(text),version_marker:ver(text),worker_marker:wmark(text),...ext(text,clamp(a.max_chars,12000,1000,120000))}}
async function compareSourceToLive(env,a={}){const[live,src,smoke]=await Promise.all([getScriptContent(env,a),getGithubSource(env,a).catch(e=>({ok:false,error:String(e.message||e)})),a.smoke===false?null:smokeLive(env,a).catch(e=>({ok:false,error:String(e.message||e)}))]);return{ok:true,exact_hash_match:!!(live.ok&&src.ok&&live.sha256===src.sha256),version_match:!!(live.ok&&src.ok&&live.version_marker&&src.version_marker&&live.version_marker===src.version_marker),worker_marker_match:!!(live.ok&&src.ok&&live.worker_marker&&src.worker_marker&&live.worker_marker===src.worker_marker),live:live.ok?{sha256:live.sha256,version_marker:live.version_marker,worker_marker:live.worker_marker,source:live.source,content_type:live.content_type,total_chars:live.total_chars}:live,github_source:src.ok?{owner:src.owner,repo:src.repo,ref:src.ref,path:src.path,sha:src.sha,sha256:src.sha256,version_marker:src.version_marker,worker_marker:src.worker_marker,total_chars:src.total_chars}:src,smoke}}
function compact(e){return{script_name:e.script_name,settings:e.settings&&e.settings.ok===false?e.settings:{script:e.settings&&e.settings.script,settings:e.settings&&e.settings.settings,subdomain:e.settings&&e.settings.subdomain,errors:e.settings&&e.settings.errors},deployments:e.deployments&&e.deployments.ok===false?e.deployments:{source:e.deployments&&e.deployments.source,count:e.deployments&&e.deployments.count,items:A(e.deployments&&e.deployments.items).slice(0,5),attempts:e.deployments&&e.deployments.attempts},routes:e.routes&&e.routes.ok===false?e.routes:{count:e.routes&&e.routes.count,routes:e.routes&&e.routes.routes,custom_domains:e.routes&&e.routes.custom_domains,attempts:e.routes&&e.routes.attempts},compare:e.compare}}
function fallback(e){let out=`Cloudflare deployment investigation for ${e.script_name}.`;if(e.settings&&e.settings.script)out+=` Worker metadata was found${e.settings.script.modified_on?`; modified_on=${e.settings.script.modified_on}`:''}.`;if(e.settings&&e.settings.subdomain&&e.settings.subdomain.workers_dev_url)out+=` workers.dev URL: ${e.settings.subdomain.workers_dev_url}.`;if(e.deployments&&e.deployments.source)out+=` Deployment history endpoint '${e.deployments.source}' returned ${e.deployments.count||0} item(s).`;if(e.routes)out+=` Route/domain evidence count: ${(e.routes.routes||[]).length+(e.routes.custom_domains||[]).length}.`;if(e.compare&&e.compare.live&&e.compare.github_source)out+=` Source comparison: exact_hash_match=${e.compare.exact_hash_match}, version_match=${e.compare.version_match}, worker_marker_match=${e.compare.worker_marker_match}.`;const sm=e.compare&&e.compare.smoke;if(sm&&sm.ok)out+=` Live smoke check ${sm.url} returned HTTP ${sm.status}${sm.detected&&sm.detected.version?` with version ${sm.detected.version}`:''}.`;if(sm&&sm.ok===false)out+=` Live smoke check failed: ${sm.error}.`;return out}
async function ai(env,e,q){if(!env.AI)return null;const prompt='Use only this JSON evidence. Explain whether the live Cloudflare Worker deployment matches repo source, whether workers.dev/routes are active, current deployment state, and uncertainty. Recommend read-only next checks only.\n\nQuestion: '+q+'\n\nEvidence:\n'+JSON.stringify(e,null,2).slice(0,42000);const o=await env.AI.run(MODEL,{messages:[{role:'user',content:prompt}],max_tokens:1800});return s(o.response||o.result||o.output_text)}
async function investigate(env,a={}){const t=T(),sc=script(env,a);t.go('settings');const set=await getWorkerSettings(env,a).catch(e=>({ok:false,error:String(e.message||e)}));t.go('deployments');const dep=await getDeploymentHistory(env,a).catch(e=>({ok:false,error:String(e.message||e)}));t.go('routes');const routes=await listRoutes(env,a).catch(e=>({ok:false,error:String(e.message||e)}));t.go('compare');const cmp=await compareSourceToLive(env,a).catch(e=>({ok:false,error:String(e.message||e)}));const evidence={script_name:sc,settings:set,deployments:dep,routes,compare:cmp};t.go('synthesis');const answer=await ai(env,evidence,s(a.question||'Determine if the live Cloudflare Worker is actually fixed and matches the GitHub source.')).catch(()=>null)||fallback(evidence);return{ok:true,flow:'cloudflare_deploy_investigation',answer,evidence:a.include_raw?evidence:compact(evidence),timings:t.done()}}
function status(env){return{ok:true,worker:WORKER,deployed_as:env.WORKER_NAME||null,version:VERSION,mode:'read_only_cloudflare_deploy_investigator',model_default:MODEL,bindings:{AI:!!env.AI,WORKER_NAME:!!env.WORKER_NAME,CLOUDFLARE_ACCOUNT_ID:!!acct(env,{}),CLOUDFLARE_API_TOKEN:!!cfTok(env),GITHUB_TOKEN:!!ghTok(env),ACCOUNT_SUBDOMAIN:!!(env.ACCOUNT_SUBDOMAIN||env.CF_ACCOUNT_SUBDOMAIN)},tools:['subagent_status','list_workers','get_worker_settings','get_deployment_history','get_script_content','list_worker_routes','smoke_live_worker','get_github_source','compare_source_to_live','investigate_cloudflare_deploy']}}
const S=[
{name:'subagent_status',description:'Health check: Cloudflare Deploy Investigator bindings, read-only mode, model, and tool list.',inputSchema:{type:'object',properties:{},required:[]}},
{name:'list_workers',description:'List Cloudflare Workers in the account. Read-only deployment inventory.',inputSchema:{type:'object',properties:{account_id:{type:'string'},query:{type:'string'},limit:{type:'number'}},required:[]}},
{name:'get_worker_settings',description:'Read one Worker deployment state: metadata, settings, bindings, usage model, and workers.dev subdomain. Read-only.',inputSchema:{type:'object',properties:{account_id:{type:'string'},script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'}},required:[]}},
{name:'get_deployment_history',description:'Read deployment/version history for one Cloudflare Worker when the account API exposes it. Read-only.',inputSchema:{type:'object',properties:{account_id:{type:'string'},script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'},limit:{type:'number'}},required:[]}},
{name:'get_script_content',description:'Fetch current deployed Worker script content or content metadata and return SHA-256/version markers. Read-only.',inputSchema:{type:'object',properties:{account_id:{type:'string'},script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'},max_chars:{type:'number'}},required:[]}},
{name:'list_worker_routes',description:'Read routes and custom domains pointing at a Worker. Uses zone_id for classic routes when provided. Read-only.',inputSchema:{type:'object',properties:{account_id:{type:'string'},zone_id:{type:'string'},script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'}},required:[]}},
{name:'smoke_live_worker',description:'HTTP smoke check a Worker URL, usually /status, to separate deployed API state from live behavior. Read-only.',inputSchema:{type:'object',properties:{script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'},workers_dev_url:{type:'string'},live_url:{type:'string'},url:{type:'string'},path:{type:'string'},status_path:{type:'string'},method:{type:'string'},max_chars:{type:'number'}},required:[]}},
{name:'get_github_source',description:'Fetch GitHub source file and return SHA-256/version markers for comparing repo source to live Worker script. Read-only.',inputSchema:{type:'object',properties:{owner:{type:'string'},repo:{type:'string'},ref:{type:'string'},branch:{type:'string'},path:{type:'string'},source_path:{type:'string'},github_path:{type:'string'},max_chars:{type:'number'}},required:[]}},
{name:'compare_source_to_live',description:'Compare current deployed Cloudflare Worker script hash/version markers to GitHub source and optionally smoke-test live URL. Read-only.',inputSchema:{type:'object',properties:{account_id:{type:'string'},script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'},owner:{type:'string'},repo:{type:'string'},ref:{type:'string'},branch:{type:'string'},path:{type:'string'},source_path:{type:'string'},github_path:{type:'string'},workers_dev_url:{type:'string'},live_url:{type:'string'},url:{type:'string'},status_path:{type:'string'},smoke:{type:'boolean'},max_chars:{type:'number'}},required:[]}},
{name:'investigate_cloudflare_deploy',description:'ONE-CALL Cloudflare deploy investigation: Worker state, settings, workers.dev URL, routes/domains, deployment history, source/live comparison, and smoke check. Read-only.',inputSchema:{type:'object',properties:{account_id:{type:'string'},zone_id:{type:'string'},script_name:{type:'string'},worker:{type:'string'},worker_name:{type:'string'},owner:{type:'string'},repo:{type:'string'},ref:{type:'string'},branch:{type:'string'},path:{type:'string'},source_path:{type:'string'},github_path:{type:'string'},workers_dev_url:{type:'string'},live_url:{type:'string'},url:{type:'string'},status_path:{type:'string'},smoke:{type:'boolean'},include_raw:{type:'boolean'},question:{type:'string'},limit:{type:'number'}},required:[]}}
];
async function run(env,name,a={}){if(name==='subagent_status')return status(env);if(name==='list_workers')return listWorkers(env,a);if(name==='get_worker_settings')return getWorkerSettings(env,a);if(name==='get_deployment_history')return getDeploymentHistory(env,a);if(name==='get_script_content')return getScriptContent(env,a);if(name==='list_worker_routes')return listRoutes(env,a);if(name==='smoke_live_worker')return smokeLive(env,a);if(name==='get_github_source')return getGithubSource(env,a);if(name==='compare_source_to_live')return compareSourceToLive(env,a);if(name==='investigate_cloudflare_deploy')return investigate(env,a);throw new Error('Unknown tool: '+name)}
async function mcp(req,env){const rpc=await B(req),id=rpc.id==null?null:rpc.id;try{if(rpc.method==='initialize')return J({jsonrpc:'2.0',id,result:{protocolVersion:'2024-11-05',capabilities:{tools:{}},serverInfo:{name:WORKER,version:VERSION}}});if(rpc.method==='notifications/initialized')return new Response(null,{status:204,headers:CORS});if(rpc.method==='ping')return J({jsonrpc:'2.0',id,result:{}});if(rpc.method==='tools/list')return J({jsonrpc:'2.0',id,result:{tools:S}});if(rpc.method==='tools/call'){let result;try{result=await run(env,rpc.params&&rpc.params.name,rpc.params&&rpc.params.arguments||{})}catch(e){result={ok:false,error:String(e.message||e)}}return J({jsonrpc:'2.0',id,result:{content:[{type:'text',text:JSON.stringify(result,null,2)}],isError:result&&result.ok===false}})}return J({jsonrpc:'2.0',id,error:{code:-32601,message:'Method not found'}})}catch(e){return J({jsonrpc:'2.0',id,error:{code:-32603,message:String(e.message||e)}})}}
export default{async fetch(req,env){const url=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});try{if(url.pathname==='/'||url.pathname==='/status'||url.pathname==='/health')return J(status(env));if(url.pathname==='/tools')return J({ok:true,tools:S});if(url.pathname==='/mcp')return mcp(req,env);if(req.method==='POST'&&url.pathname==='/call'){const b=await B(req);try{return J(await run(env,b.name,b.arguments||{}))}catch(e){return J({ok:false,error:String(e.message||e)},200)}}return J({ok:false,error:'not_found',worker:WORKER},404)}catch(e){return J({ok:false,error:String(e.message||e),worker:WORKER},500)}}};